version: '3.8'

services:
  node:
    # Use the official Node.js 16 image as a base
    image: node:16
    # Set the working directory in the container
    working_dir: /app
    # Copy package.json and package-lock.json to the working directory
    volumes:
      - .:/app
    # Install Node.js dependencies
    command: npm install
    # Expose port for Node.js
    ports:
      - "3000:3000"
  
  nginx:
    # Use the official Nginx image
    image: nginx
    # Mount the React app's build directory as the Nginx web root

  volumes:
    - ./build:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/nginx.conf:ro

    # Expose port for Nginx
    ports:
      - "80:80"
